title: EyePoint Access
email: info@eyepointaccess.com
baseurl: ""
domain: "eyepointaccess.com"
url: "https://eyepointaccess.com"

logo: assets/logo.png

exclude:
  - README.md
  - serve
  - "*.code-workspace"
